# -*- coding: utf-8 -*-
"""musees_france.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KqD01wIhSYfFWcYwK3vbT3LKkvD5itJ2

# Analyse avancée des Musées de France  
Cartographie interactive, typologies et enrichissement visuel

Ce notebook propose une exploration approfondie des musées de France à partir de données publiques.  
Nous allons combiner analyse statistique, visualisation géographique interactive et enrichissement visuel via l’API Wikimedia Commons.

Objectifs :
- comprendre la répartition territoriale des musées  
- analyser les typologies et caractéristiques institutionnelles  
- créer une carte interactive avec clusters  
- enrichir les données avec images et liens utiles  
- produire une table finale exploitable pour un portfolio ou un tableau de bord  

---

## 1. Importation des bibliothèques
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import folium
from folium.plugins import MarkerCluster
import requests

sns.set(style="whitegrid", palette="deep")

"""## 2. Chargement du dataset

Le fichier `musees-de-france.csv` doit être importé dans l’environnement Colab.

"""

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("musees-de-france.csv", sep=";")
df.head()

"""## 3. Aperçu général du dataset

"""

df.info()
df.describe(include="all")

"""## 4. Nettoyage et préparation

"""

df = df.drop_duplicates()

df["Région administrative"] = df["Région administrative"].str.strip().str.title()
df["Département"] = df["Département"].astype(str)

df.isna().sum()

"""## 5. Répartition des musées par région

"""

plt.figure(figsize=(12,6))
df["Région administrative"].value_counts().sort_values().plot(kind="barh")
plt.title("Nombre de musées par région")
plt.xlabel("Nombre de musées")
plt.ylabel("Région")
plt.show()

"""## 6. Classification thématique automatique (basée sur le nom du musée)

"""

def extract_museum_type(name):
    name = str(name).lower()
    if 'art' in name or 'beaux-arts' in name:
        return 'Art'
    elif 'histoire' in name or 'guerre' in name:
        return 'Histoire'
    elif 'science' in name or 'technique' in name:
        return 'Science & Technique'
    elif 'archéologie' in name:
        return 'Archéologie'
    elif 'ethno' in name or 'tradition' in name:
        return 'Ethnologie & Traditions'
    elif 'nature' in name or 'environnement' in name:
        return 'Histoire Naturelle'
    elif 'pêche' in name or 'mer' in name:
        return 'Musée Maritime'
    elif 'château' in name:
        return 'Château & Domaine'
    else:
        return 'Autre'

df["Type de musée"] = df["Nom officiel du musée"].apply(extract_museum_type)

plt.figure(figsize=(12,6))
df["Type de musée"].value_counts().plot(kind="bar")
plt.title("Types de musées les plus représentés")
plt.xticks(rotation=45)
plt.show()

"""## 7. Répartition par département

"""

plt.figure(figsize=(12,15))
df["Département"].value_counts().sort_values().plot(kind="barh")
plt.title("Répartition des musées par département")
plt.xlabel("Nombre de musées")
plt.show()

"""# 8. Carte interactive avancée (Folium + clusters)"""

mean_lat = df["Latitude"].mean()
mean_lon = df["Longitude"].mean()

m = folium.Map(location=[mean_lat, mean_lon], zoom_start=6)
cluster = MarkerCluster().add_to(m)

for _, row in df.iterrows():
    popup = f"""
    <b>{row['Nom officiel du musée']}</b><br>
    {row['Commune']} ({row['Département']})<br>
    <a href="{row['URL']}" target="_blank">Site officiel</a>
    """
    folium.Marker(
        location=[row["Latitude"], row["Longitude"]],
        popup=popup,
        tooltip=row["Nom officiel du musée"]
    ).add_to(cluster)

m

"""# 9. Enrichissement visuel : récupération d’images via Wikimedia Commons

Nous allons interroger l’API Wikimedia Commons pour récupérer une image libre associée au nom du musée.
"""

def get_commons_image(query):
    url = "https://commons.wikimedia.org/w/api.php"
    params = {
        "action": "query",
        "format": "json",
        "prop": "pageimages",
        "piprop": "thumbnail",
        "pithumbsize": 300,
        "generator": "search",
        "gsrsearch": query,
        "gsrlimit": 1
    }
    response = requests.get(url, params=params)

    if response.status_code == 200:
        try:
            data = response.json()
            pages = data["query"]["pages"]
            page = next(iter(pages.values()))
            return page["thumbnail"]["source"]
        except (requests.exceptions.JSONDecodeError, KeyError, StopIteration) as e:
            # print(f"Error parsing JSON or extracting data for query '{query}': {e}") # For debugging
            # print(f"Raw response text: {response.text}") # For debugging
            return None
    else:
        # print(f"API request failed for query '{query}' with status code {response.status_code}") # For debugging
        # print(f"Raw response text: {response.text}") # For debugging
        return None

df["Image"] = df["Nom officiel du musée"].apply(get_commons_image)
df.head()

"""# 10. Tableau enrichi (nom, ville, contact, site, image)"""

table = df[[
    "Nom officiel du musée",
    "Commune",
    "Département",
    "Téléphone",
    "URL",
    "Image"
]]

table.head(10)

"""# 11. Affichage d’un tableau HTML avec images"""

from IPython.display import HTML

def make_html_table(df):
    html = "<table>"
    html += "<tr><th>Musée</th><th>Commune</th><th>Contact</th><th>Site</th><th>Image</th></tr>"
    for _, row in df.iterrows():
        img = f'<img src="{row["Image"]}" width="200">' if row["Image"] else "—"
        html += f"""
        <tr>
            <td>{row['Nom officiel du musée']}</td>
            <td>{row['Commune']} ({row['Département']})</td>
            <td>{row['Téléphone']}</td>
            <td><a href="{row['URL']}" target="_blank">Lien</a></td>
            <td>{img}</td>
        </tr>
        """
    html += "</table>"
    return HTML(html)

make_html_table(table.head(20))

"""# 12. Conclusion

Ce notebook avancé a permis de :

- analyser les musées de France selon plusieurs dimensions  
- produire des visualisations statistiques  
- créer une carte interactive avec clusters  
- enrichir les données avec images et liens  
- générer une table finale exploitable pour un portfolio  

Il constitue une base solide pour un tableau de bord culturel ou un projet de data storytelling.
"""